// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_PAUS, KC_1, KC_2,      KC_3, KC_4,   KC_5,    KC_F4,   KC_F5,   KC_F12,      KC_6, KC_7, KC_8,    KC_9,   KC_0,    KC_GRV,
        KC_TAB,  KC_Q, KC_W,      KC_E, KC_R,   KC_T,    KC_F8,   KC_UP,   SGUI(KC_S),  KC_Y, KC_U, KC_I,    KC_O,   KC_P,    KC_LBRC,
        KC_LCTL, KC_A, KC_S,      KC_D, KC_F,   KC_G,    KC_LEFT, KC_DOWN, KC_RGHT,     KC_H, KC_J, KC_K,    KC_L,   KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z, KC_X,      KC_C, KC_V,   KC_B,    KC_Z,    KC_X,    KC_C,        KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LALT,
        LGUI_T(KC_ESC), LGUI_T(KC_ESC), KC_SPC, TL_LOWR,      KC_DEL, KC_LBRC,          TL_UPPR, KC_ENT, LCA(KC_EQL),     LCA(KC_EQL)
    ),
    [1] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX,
        _______, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX,  C(KC_X), C(KC_HOME), KC_UP,   C(KC_END), XXXXXXX, XXXXXXX,
        _______, KC_F14,  KC_MPLY, KC_VOLD, KC_VOLU, S(KC_CAPS),  XXXXXXX, XXXXXXX, XXXXXXX,  C(KC_V), KC_LEFT,    KC_DOWN, KC_RGHT,   XXXXXXX, _______,
        _______, XXXXXXX, XXXXXXX, KC_MPRV, KC_MNXT, C(KC_W),     XXXXXXX, XXXXXXX, XXXXXXX,  C(KC_C), KC_HOME,    KC_END,  XXXXXXX,   XXXXXXX, XXXXXXX,
        _______,                   _______, _______, _______,          _______, _______,      _______, _______,    _______,                     _______
    ),
    [2] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,    XXXXXXX, XXXXXXX, XXXXXXX,  KC_F6,   KC_F7,   KC_I,    KC_O,    KC_F8,   XXXXXXX,
        _______, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,     XXXXXXX, XXXXXXX, XXXXXXX,  KC_F10,  KC_BSPC, KC_K,    KC_L,    KC_F13,  _______,
        _______, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,     XXXXXXX, XXXXXXX, XXXXXXX,  KC_F12,  KC_F11,  KC_COMM, KC_DOT,  KC_SLSH, XXXXXXX,
        _______,                   _______, _______, _______,       _______, _______,      _______, _______, _______,                   _______
    ),
    [3] = LAYOUT(
        XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX,    XXXXXXX,    XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX,    XXXXXXX,   XXXXXXX,
        _______, S(KC_1),    S(KC_2), S(KC_RBRC), S(KC_BSLS), S(KC_5),      XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX,    XXXXXXX,   XXXXXXX,
        _______, S(KC_6),    S(KC_7), S(KC_8),    S(KC_9),    LCA(KC_TAB),  XXXXXXX, XXXXXXX, XXXXXXX,  S(KC_INT3), S(KC_SCLN), KC_MINS, S(KC_QUOT), KC_INT3,   _______,
        _______, S(KC_MINS), KC_EQL,  KC_RBRC,    KC_BSLS,    S(KC_LBRC),   XXXXXXX, XXXXXXX, XXXXXXX,  S(KC_INT1), S(KC_3),    S(KC_4), KC_INT1,    S(KC_EQL), XXXXXXX,
        _______,                      _______,    _______,    XXXXXXX,           XXXXXXX, XXXXXXX,      XXXXXXX,    _______,    _______,                        _______
    ),
    [4] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX
    ),
    [5] = LAYOUT(
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,      XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX
    )
};
